### PR TITLE
Updating instructions for NANOAODv6

### PR DESCRIPTION
**Pull request by trtomei**

### CODE REVIEW

**Comment by hqucms** [comment]
I have updated the cmsDriver commands based on NanoV6 in https://gitlab.cern.ch/hqu/NanoTuples/blob/prod/102X/README.md. Hope that helps:)

**Comment by mcremone** [comment]
@hqucms can you comment on the possibility to add JEC/JER to AK15 during the NanoAOD generation? The discussion is here: https://github.com/LPC-DM/NanoHarvester/issues/16

**Comment by areinsvo** [comment]
@hqucms thanks for pointing us to your updated README! One thing I noticed was that for 2016 and 2017 data, we are using --conditions 102X_dataRun2_v12 whereas you have --conditions 102X_dataRun2_v11. 
 
v11 is the recommended version according to the [PPD table](https://docs.google.com/presentation/d/1YTANRT_ZeL5VubnFq7lNGHKsiD7D3sDiOPNgXUYVI0I/edit#slide=id.g6238171b20_10_0), but v12 is the recommended version according to the [twiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVDataReprocessingNanoAODv6)with instructions for NanoAODv6

**Comment by hqucms** [comment]
@areinsvo I think the two GTs should be equivalent for 16/17, but since official v6 samples are produced w/ `102X_dataRun2_v12` maybe it's better to stick to that.

**Comment by areinsvo** [comment]
Thanks Thiago! I will go ahead and merge this.

**Pull request merged**
